version: "3.8"

services:
  product-service:
    build: ./services/product-service
    container_name: product-service
    ports:
      - "8081:8081"
    networks:
      - ecommerce-net

  user-service:
    build: ./services/user-service
    container_name: user-service
    ports:
      - "8080:8080"
    env_file:
      - ./services/user-service/.env
    depends_on:
      - product-service
    networks:
      - ecommerce-net
    restart: always  

networks:
  ecommerce-net:
    driver: bridge